const PIN='2025',AUTH_KEY='ypo_auth',AUTH_HOURS=8;
const ROLES=['Chapter Chair','Officer Chair','Learning Chair','Forum Chair','Membership Chair','Spouse/Partner Chair','YPO Gold Liaison'];
function nowISO(){return new Date().toISOString()}function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function getStore(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}function setStore(k,v){localStorage.setItem(k,JSON.stringify(v))}
function isAuthed(){let a=getStore(AUTH_KEY,null);return a&&a.expiry>Date.now()}function setAuth(){setStore(AUTH_KEY,{expiry:Date.now()+AUTH_HOURS*3600000})}function logout(){localStorage.removeItem(AUTH_KEY);location.href='index.html'}
function requireAuth(){if(!isAuthed()&&!location.pathname.endsWith('index.html'))location.href='index.html'}
async function loadNav(active){let el=document.getElementById('nav');if(!el)return;el.innerHTML=await fetch('./nav.html').then(r=>r.text());document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===active)a.classList.add('active')});}
function footer(){let f=document.createElement('footer');f.className='footer';f.textContent='YPO Gold Board Operations · Confidential';document.body.appendChild(f)}
function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function csv(name,rows){if(!rows.length)return toast('Nothing to export');let heads=Object.keys(rows[0]);let out=[heads.join(','),...rows.map(r=>heads.map(h=>'"'+String(r[h]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function seed(){if(!localStorage.getItem('ypo_training')){setStore('ypo_training',Object.fromEntries(ROLES.map(r=>[r,{checks:[false,false,false],resources:[{title:'YPO Gold Board Resource Center',url:'#'}],notes:''}])))}
if(!localStorage.getItem('ypo_events'))setStore('ypo_events',[{id:uid('ev'),name:'Gold Board Strategy Retreat',date:'2026-06-12',location:'Seattle, WA',type:'Board Meeting',attendance:14,score:9,notes:'Annual planning and governance alignment.',status:'Upcoming'},{id:uid('ev'),name:'Member Forum Exchange',date:'2026-04-18',location:'Portland, OR',type:'Forum',attendance:32,score:8,notes:'Strong engagement and forum best-practice sharing.',status:'Completed'},{id:uid('ev'),name:'Leadership Learning Dinner',date:'2026-07-22',location:'San Francisco, CA',type:'Learning',attendance:45,score:0,notes:'Speaker TBD.',status:'Upcoming'}]);
if(!localStorage.getItem('ypo_members'))setStore('ypo_members',[{id:uid('mem'),first:'Sarah',last:'Whitman',company:'Whitman Ventures / CEO',email:'sarah@example.com',phone:'206-555-0148',dob:'1976-09-14',join:'2014-03-01',role:'Chapter Chair',status:'Active',notes:'Board lead.'},{id:uid('mem'),first:'David',last:'Chen',company:'Northline Capital / Managing Partner',email:'david@example.com',phone:'415-555-0191',dob:'1982-02-07',join:'2019-10-15',role:'Learning Chair',status:'Active',notes:'Learning calendar owner.'},{id:uid('mem'),first:'Maya',last:'Patel',company:'Patel Foods / President',email:'maya@example.com',phone:'503-555-0172',dob:'1980-12-02',join:'2021-05-20',role:'',status:'Prospective',notes:'Approaching Gold eligibility.'}]);
if(!localStorage.getItem('ypo_docs'))setStore('ypo_docs',[{id:uid('doc'),title:'Chapter Bylaws',category:'Bylaws',description:'Current governing bylaws for board reference.',url:'#',date:'2026-01-15',version:'3.2',pinned:true},{id:uid('doc'),title:'Board Meeting Minutes Template',category:'Templates',description:'Standard template for monthly board minutes.',url:'#',date:'2026-03-08',version:'1.0',pinned:true},{id:uid('doc'),title:'Membership Policy Guide',category:'Policies',description:'Membership qualification and transition guidance.',url:'#',date:'2026-02-11',version:'2.1',pinned:false}]);}
function age(dob){if(!dob)return '';let d=new Date(dob),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function scoreBadge(s){let n=Number(s);return n>=8?'green':n>=5?'amber':n>=1?'red':''}
requireAuth();seed();